### ISSUE TITLE
one link gives 404

### ISSUE THREAD

**Issue by gspia** [hansroland/reflex-dom-inbits#12]
Thanks for the great guide! 

One minor issue on line "This is defined in the module Reflex.Dom.Builder.Class.Events:": the link gives 404.

**Comment by hansroland** [comment]
Thanks for reporting this issue. In the _reflex-dom_ repository they moved a lot of modules (including  _Events.hs_) from the `reflex-dom` to the `reflex-dom-core` directory. I adapted the link.
Linking to foreign repositories is considered harmful...
