### ISSUE TITLE
src/count01.hs: When using native GTK mode, the "ClickMe" label does not appear

### ISSUE THREAD

**Issue by mantkiew** [hansroland/reflex-dom-inbits#2]
In fact, the whole button is invisible. It works for ghcjs as expected.

Also, the "Try it!" part should contain some instructions such as 

```
cd ~/reflex-platform
./try-reflex
cd ~reflex-dom-inbits
ghc src/count01.hs
src/count01
ghcjs src/count01.hs
firefox src/count01.jsexe/index.html
```

that is not totally obvious for beginners. Especially that reflex-platform encourages using `workOn`, which cannot be used here.

**Comment by hansroland** [comment]
**Re WebkitGTK:**
I installed WebkitGtk, reflex, reflex-dom etc normally with cabal and I never had any issues. Today I tested WebkitGtk first time in the nix shell created by ./try-reflex from reflex-platform and to my surprise it just worked. I'm using Linux Debian 8 (Jessie). What is your OS? Did you experience similar problems in the other examples?

**Re "Try it!":**
You are right! I replaced the "Try it" with a little section, explaining how to run the program in the nix shell.

**Comment by mantkiew** [comment]
I am on Ubuntu 16.04.2. In fact, none of the other elements (checkboxes, textinputs, etc.) appear. Very strange.

**Comment by hansroland** [comment]
Yes, very strange. 
Did you try one of the examples in [https://github.com/reflex-frp/reflex-examples](https://github.com/reflex-frp/reflex-examples)? Attention, not all of these examples are adapted to reflex-dom-0.4.
Did you try with an other browser? I did most of my tests with Chromium.

I don't think, this is an issue of my tutorial. Do you mind if I close this issue?

**Comment by hansroland** [comment]
OP didn't answer question "ok to close" within one month.
